"""creazione

Revision ID: 27c6680c0cee
Revises: 
Create Date: 2020-12-02 11:40:11.484510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c6680c0cee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('anabasi_vendite', sa.Boolean(), nullable=False),
    sa.Column('anabasi_finanaza', sa.Boolean(), nullable=False),
    sa.Column('anabasi_co_an', sa.Boolean(), nullable=False),
    sa.Column('anabasi_produco', sa.Boolean(), nullable=False),
    sa.Column('anabasi_logistica', sa.Boolean(), nullable=False),
    sa.Column('anabasi_crisi', sa.Boolean(), nullable=False),
    sa.Column('link_workset', sa.String(length=250), nullable=True),
    sa.Column('link_anabasi_vend', sa.String(length=250), nullable=True),
    sa.Column('link_anabasi_fina', sa.String(length=250), nullable=True),
    sa.Column('link_anabasi_co_an', sa.String(length=250), nullable=True),
    sa.Column('link_anabasi_produco', sa.String(length=250), nullable=True),
    sa.Column('link_anabasi_logistica', sa.String(length=250), nullable=True),
    sa.Column('link_anabasi_crisi', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
